import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <header>
          <Link href={"/"}>Index</Link>
          &nbsp;&nbsp;&nbsp;
          <Link href={"/search"}>Search</Link>
          &nbsp;&nbsp;&nbsp;
          <Link href={"/book/1"}>Book-1</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
